# Configuration de synchronisation des références Roo-Code

include:
  - README.md
  - rules-agents.md
  - rules-code.md
  - rules-debug.md
  - rules-documentation.md
  - rules-maintenance.md
  - rules-migration.md
  - rules-orchestration.md
  - rules-plugins.md
  - rules-security.md
  - rules.md
  - tools-registry.md
  - workflows-matrix.md

exclude: []

format:
  section: "## Références croisées"
  item: "- [{{file}}]({{path}}): {{description}}"

personnalisation:
  description_default: "Lien documentaire Roo-Code"
  position: "fin"
  sync_mode: "auto"
