version: "1" # or "2", depending on the schema version expected by golangci-lint
run:
  timeout: 5m
  issues-exit-code: 1
  tests: false
  skip-dirs:
    - vendor
    - test

linters-settings:
  govet:
    check-shadowing: true

  golint:
    min-confidence: 0.8

  staticcheck:
    checks: ["all"]

  errcheck:
    check-blank: true

linters:
  enable-all: true
  disable:
    - prealloc
    - gochecknoglobals
    - gochecknoinits
    - exhaustivestruct
    - wrapcheck
    - nlreturn
    - funlen
    - gofumpt # Use gofmt directly
    - testpackage
    - wsl
    - paralleltest
    - nosnakecase
    - varnamelen
    - depguard
    - godox
    - ireturn
    - tagliatelle
    - goheader
    - nonamedreturns
    - nakedret
    - revive # golint is preferred
    - interfacer # Deprecated
    - scopelint # Deprecated
    - maligned # Deprecated
    - deadcode # Deprecated
    - varcheck # Deprecated
    - structcheck # Deprecated
    - ifshort # Deprecated
    - rowserrcheck # Deprecated
    - sqlclosecheck # Deprecated
    - dupl
    - lll
    - cyclop
    - gocognit
