# BranchingManager Configuration
# Ultra-Advanced 8-Level Branching Framework

# Level 1: Micro-Sessions Temporelles (30min timestamped sessions)
default_session_duration: 30m
max_session_duration: 4h
session_naming_pattern: "session-{{.ID}}-{{.Timestamp}}"
auto_archive_enabled: true

# Level 2: Event-Driven Branching (automatic triggers)
event_queue_size: 1000
git_hooks_enabled: true
auto_branching_enabled: true
event_processing_timeout: 30s

# Level 3: Multi-Dimensional Branching (tags/classifications)
max_dimensions: 10
tagging_enabled: true
dimension_weight_enabled: true

# Level 4: Contextual Memory Integration (auto-documentation)
auto_documentation_enabled: true
memory_integration_enabled: true
context_linking_enabled: true

# Level 5: Temporal Branching & Time-Travel (hourly snapshots)
snapshot_interval: 1h
max_snapshots_per_branch: 168 # 1 week of hourly snapshots
time_travel_enabled: true

# Level 6: Predictive Branching (AI-powered optimization)
predictive_enabled: true
ai_model_path: "/models/branching_predictor.bin"
prediction_confidence_threshold: 0.75

# Level 7: Branching as Code (declarative configuration)
code_execution_enabled: true
supported_languages:
  - yaml
  - json
  - go
  - lua
code_validation_enabled: true

# Level 8: Quantum Branching (parallel development approaches)
quantum_branching_enabled: true
max_parallel_approaches: 5
approach_selection_ai: true

# Database Configuration
database_url: "postgresql://user:password@localhost:5432/branching_db"
vector_database_url: "http://localhost:6333"

# Monitoring and Logging
metrics_enabled: true
log_level: "info"

# Integration Settings
storage_manager_enabled: true
error_manager_enabled: true
contextual_memory_enabled: true

# Git Configuration
git_executable: "git"
default_base_branch: "main"
branch_prefix_patterns:
  feature: "feature/"
  bugfix: "bugfix/"
  hotfix: "hotfix/"
  experiment: "exp/"
  refactor: "refactor/"

# n8n Integration
n8n_webhook_url: "http://localhost:5678/webhook/branching"
n8n_api_key: "${N8N_API_KEY}"
n8n_workflows:
  session_created: "workflow-session-created"
  branch_merged: "workflow-branch-merged"
  snapshot_created: "workflow-snapshot-created"

# MCP Gateway Integration
mcp_gateway_url: "http://localhost:8080"
mcp_api_endpoints:
  sessions: "/api/v1/sessions"
  branches: "/api/v1/branches"
  events: "/api/v1/events"
  snapshots: "/api/v1/snapshots"

# Security Settings
api_rate_limit: 100 # requests per minute
max_branch_depth: 10
session_timeout: 30m
webhook_secret: "${WEBHOOK_SECRET}"

# Performance Settings
worker_pool_size: 10
batch_size: 100
cache_ttl: 5m
connection_pool_size: 20

# Feature Flags
features:
  experimental_quantum: false
  advanced_ai_predictions: true
  real_time_collaboration: false
  distributed_branching: false
