# 📈 Grafana Provisioning - Data Sources
# Automatically configure Prometheus as data source

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "5s"
      queryTimeout: "60s"
      httpMethod: "POST"
    secureJsonData: {}

  - name: Prometheus-External
    type: prometheus
    access: proxy
    url: http://localhost:9091
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "30s"
      httpMethod: "GET"
