#
# Module manifest for module 'PSCacheManager'
#
# Generated by: Augment Agent (Improved by AI)
#
# Generated on: 2023-10-27 (Update Date)
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PSCacheManager.psm1'

# Version number of this module. **Incremented for major changes.**
ModuleVersion = '2.0.0'

# Supported PSEditions (Desktop for .NET Framework, Core for .NET Core/.NET 5+)
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module. DO NOT CHANGE.
GUID = '8f7b1c9a-5b4a-4e3d-8c7d-9e1f2b3a4c5d'

# Author of this module
Author = 'Augment Agent'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) 2024 Augment Agent. All rights reserved.' # Updated year

# Description of the functionality provided by this module. **Updated for v2.0**
Description = 'Provides an optimized, thread-safe caching solution for PowerShell 5.1+. Features include memory and persistent disk caching (using CliXml for object fidelity), configurable TTL, LRU/LFU eviction policies, optional TTL extension on access, and tag-based management.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# PowerShell 5.1 requires .NET 4.5.2 or later.
DotNetFrameworkVersion = '4.5.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
CLRVersion = '4.0'

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, list functions explicitly. **Updated**
FunctionsToExport = @(
    'New-PSCache',
    'Get-PSCacheItem',
    'Set-PSCacheItem',
    'Remove-PSCacheItem',
    'Test-PSCacheItem', # Added new function
    'Get-PSCacheStatistics',
    'Clear-PSCache'
)

# Cmdlets to export from this module, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module. **Best practice is to export none.**
VariablesToExport = @()

# Aliases to export from this module, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module. **Good practice to list them.**
FileList = @(
    'PSCacheManager.psm1',
    'PSCacheManager.psd1'
    # Add other files like 'Example-Usage.ps1' if distributing them as part of the module package
    # 'Examples\Example-Usage.ps1'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries. **Updated**
        Tags = @('Cache', 'Caching', 'Performance', 'Optimization', 'PowerShell', 'PS5.1', 'MemoryCache', 'DiskCache', 'Persistence', 'LRU', 'LFU', 'TTL', 'CliXml')

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module. **Updated for v2.0**
        ReleaseNotes = @"
Version 2.0.0:
- Major overhaul based on advanced caching strategies.
- Switched serialization from JSON to Export/Import-CliXml for better PowerShell object fidelity.
- Added Least Frequently Used (LFU) eviction policy alongside Least Recently Used (LRU).
- Added option (-ExtendTtlOnAccess) to reset Time-To-Live when an item is accessed.
- Disk cache loading is now lazy (occurs on memory miss) instead of loading all at startup.
- Improved internal structure: Renamed CleanCache -> EvictItems, ClearExpired for clarity.
- Removed unreliable object size estimation; eviction relies on MaxMemoryItems.
- Added Test-PSCacheItem function to check for key existence.
- Enhanced error handling and logging (using Write-Verbose/Warning/Error).
- Improved robustness, especially around file I/O for disk cache.
- Added more configuration options to New-PSCache (EvictionPolicy, EvictionPercentage, ExtendTtlOnAccess).
- Refined Get-PSCacheItem with -GenerateValue logic and argument passing.
- Updated documentation (comment-based help).
- Module manifest updated (FunctionsToExport, VariablesToExport=@(), Tags, ReleaseNotes).
"@

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}