# Configuration pour environnement de staging
# Email Sender - Staging Environment

environment: staging

server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s
  max_body_size: 8388608  # 8MB
  tls:
    enabled: false  # TLS handled by reverse proxy

redis:
  host: "${REDIS_HOST:-localhost}"
  port: 6379
  password: "${REDIS_PASSWORD}"
  database: 1  # Different DB from production
  pool_size: 15
  min_idle_conns: 8
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_timeout: 4s
  idle_timeout: 300s
  max_retries: 3
  retry_delay: 1s
  enable_cluster: false

email:
  smtp:
    host: "${SMTP_HOST:-smtp.mailtrap.io}"
    port: 587
    username: "${SMTP_USERNAME}"
    password: "${SMTP_PASSWORD}"
    use_tls: true
    use_ssl: false
  default_from: "${EMAIL_FROM:-staging@emailsender.dev}"
  default_from_name: "${EMAIL_FROM_NAME:-Email Sender Staging}"
  max_retries: 3
  retry_delay: 1s
  rate_limit_per_hour: 5000
  enable_tracking: true
  enable_templating: true

monitoring:
  enabled: true
  metrics_path: "/metrics"
  metrics_port: 9090
  health_check_path: "/health"
  collection_interval: 30s
  alerts_enabled: true
  alerts_webhook: "${ALERTS_WEBHOOK_URL}"
  alerts_email:
    - "${DEV_EMAIL}"
  thresholds:
    cpu_usage: 85.0
    memory_usage: 90.0
    disk_usage: 95.0
    response_time: 1s
    error_rate: 8.0
    cache_hit_rate: 60.0

security:
  enable_cors: true
  allowed_origins:
    - "${FRONTEND_URL:-http://localhost:3000}"
    - "https://staging.emailsender.dev"
  enable_rate_limit: true
  rate_limit_rps: 200
  enable_auth: true
  jwt_secret: "${JWT_SECRET}"
  jwt_expiry: 12h
  api_keys:
    - "${API_KEY_STAGING}"

logging:
  level: "debug"
  format: "json"
  output: "both"  # stdout + file
  file: "/var/log/emailsender/staging.log"
  max_size: 50
  max_backups: 3
  max_age: 14
  compress: true

cache:
  default_ttl: 1800s  # 30 minutes
  type_ttls:
    default_values: 1800s   # 30 minutes
    statistics: 21600s      # 6 hours
    ml_models: 1800s        # 30 minutes
    configuration: 900s     # 15 minutes
    user_sessions: 3600s    # 1 hour
  max_memory: "256mb"
  eviction_policy: "allkeys-lru"
  enable_metrics: true

metadata:
  version: "${APP_VERSION:-staging}"
  environment: "staging"
