# EMAIL_SENDER_1 - Conformity Rules Configuration
# Phase 2.2.2 - Centralized Configuration for ConformityManager
# This file defines the comprehensive conformity verification rules and thresholds

conformity:
  # Global conformity settings
  enabled: true
  auto_check: true
  check_interval: "1h"
  
  # Compliance level thresholds (0-100 scale)
  thresholds:
    bronze: 60.0    # Minimum acceptable conformity
    silver: 75.0    # Good conformity level
    gold: 85.0      # Excellent conformity level
    platinum: 95.0  # Outstanding conformity level
  
  # Report generation settings
  reports:
    enabled: true
    formats: ["json", "html", "markdown", "pdf", "xml"]
    output_dir: "docs/managers/conformity/reports"
    auto_generate: true
    retention_days: 30
    
  # Badge generation settings
  badges:
    enabled: true
    output_dir: "docs/managers/badges"
    formats: ["svg", "png"]
    style: "flat-square"  # flat, flat-square, plastic, for-the-badge
    
  # Notification settings
  notifications:
    enabled: true
    webhooks:
      - url: "http://localhost:8080/webhooks/conformity"
        events: ["critical_issue", "status_change", "report_generated"]
      - url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
        events: ["critical_issue"]
    
  # Manager exclusions
  excluded_managers:
    - "test-manager"
    - "mock-manager"
    
  # Required standards for all managers
  required_standards:
    - "error_integration"
    - "documentation"
    - "testing"
    - "architecture"

# Architecture conformity rules (SOLID/DRY/KISS)
architecture:
  # SOLID Principles weights and thresholds
  solid:
    enabled: true
    weight: 0.3  # 30% of total architecture score
    
    # Single Responsibility Principle
    srp:
      enabled: true
      weight: 0.2
      max_responsibilities_per_class: 3
      max_methods_per_interface: 10
      cohesion_threshold: 0.7
      
    # Open/Closed Principle  
    ocp:
      enabled: true
      weight: 0.2
      interface_usage_threshold: 0.8
      extension_points_required: true
      modification_penalty: 0.1
      
    # Liskov Substitution Principle
    lsp:
      enabled: true
      weight: 0.2
      interface_compliance_threshold: 0.9
      behavioral_compatibility_required: true
      
    # Interface Segregation Principle
    isp:
      enabled: true
      weight: 0.2
      max_interface_methods: 7
      client_specific_interfaces: true
      
    # Dependency Inversion Principle
    dip:
      enabled: true
      weight: 0.2
      abstraction_dependency_ratio: 0.8
      concrete_dependency_penalty: 0.2

  # DRY (Don't Repeat Yourself) rules
  dry:
    enabled: true
    weight: 0.35  # 35% of total architecture score
    max_duplication_percentage: 5.0
    duplicate_lines_threshold: 6
    similarity_threshold: 0.85
    exclude_patterns:
      - "test_*"
      - "*_test.go"
      - "mock_*"

  # KISS (Keep It Simple, Stupid) rules
  kiss:
    enabled: true
    weight: 0.35  # 35% of total architecture score
    max_cyclomatic_complexity: 10
    max_function_length: 50
    max_function_parameters: 5
    max_nesting_level: 4
    cognitive_complexity_threshold: 15

# Error Manager integration conformity rules
error_integration:
  enabled: true
  weight: 0.25  # 25% of total conformity score
  
  # Required ErrorManager interfaces
  required_interfaces:
    - "ErrorManager"
    - "ErrorHooks"
    
  # Required methods
  required_methods:
    - "ProcessError"
    - "CatalogError"
    - "ValidateErrorEntry"
    
  # Integration patterns
  patterns:
    error_propagation: true
    context_passing: true
    hook_registration: true
    centralized_logging: true
    
  # Error handling coverage
  coverage:
    minimum_error_handling_coverage: 0.90
    critical_path_coverage: 0.95
    error_test_coverage: 0.85

# Documentation conformity rules
documentation:
  enabled: true
  weight: 0.25  # 25% of total conformity score
  
  # README requirements
  readme:
    required: true
    min_sections: 8
    required_sections:
      - "Overview"
      - "Installation" 
      - "Usage"
      - "API Documentation"
      - "Testing"
      - "Error Handling"
      - "Integration"
      - "Examples"
    min_length: 1000  # characters
    
  # API documentation requirements
  api_docs:
    required: true
    godoc_coverage_threshold: 0.95
    exported_functions_documented: 0.95
    example_coverage: 0.80
    
  # Architecture diagrams
  diagrams:
    required: true
    formats: ["ascii", "plantuml", "mermaid"]
    min_diagrams: 2
    
  # Examples requirements
  examples:
    required: true
    min_examples: 3
    working_examples_required: true
    integration_examples: true

# Testing conformity rules
testing:
  enabled: true
  weight: 0.25  # 25% of total conformity score
  
  # Test coverage requirements
  coverage:
    minimum_line_coverage: 0.85
    minimum_branch_coverage: 0.80
    minimum_function_coverage: 0.90
    critical_path_coverage: 0.95
    
  # Test quality requirements
  quality:
    test_to_code_ratio: 0.5  # At least 50% test code
    max_test_function_length: 100
    assertion_coverage: 0.90
    mock_usage_ratio: 0.30
    
  # Test types required
  test_types:
    unit_tests: true
    integration_tests: true
    error_handling_tests: true
    performance_tests: false  # Optional
    
  # Test naming conventions
  naming:
    test_function_prefix: "Test"
    benchmark_function_prefix: "Benchmark"
    example_function_prefix: "Example"

# Code quality conformity rules
code_quality:
  enabled: true
  weight: 0.25  # 25% of total conformity score
  
  # Complexity metrics
  complexity:
    max_cyclomatic_complexity: 10
    max_cognitive_complexity: 15
    max_function_length: 50
    max_file_length: 500
    
  # Code style
  style:
    gofmt_compliant: true
    golint_compliant: true
    govet_compliant: true
    ineffassign_check: true
    
  # Comment requirements
  comments:
    min_comment_ratio: 0.20
    public_function_comments: 0.95
    package_comment_required: true
    
  # Performance considerations
  performance:
    no_obvious_performance_issues: true
    memory_leak_detection: true
    goroutine_leak_detection: true

# Ecosystem-specific rules for EMAIL_SENDER_1
ecosystem:
  # Manager-specific customizations
  manager_overrides:
    # High-priority managers with stricter requirements
    error-manager:
      architecture:
        weight: 0.40
      testing:
        coverage:
          minimum_line_coverage: 0.95
          
    config-manager:
      documentation:
        weight: 0.35
      testing:
        coverage:
          minimum_line_coverage: 0.90
          
    dependency-manager:
      architecture:
        solid:
          weight: 0.35
      code_quality:
        complexity:
          max_cyclomatic_complexity: 8
          
  # Integration requirements
  integration:
    cross_manager_communication: true
    centralized_error_handling: true
    unified_configuration: true
    consistent_logging: true
    
  # Global standards
  standards:
    go_version: "1.21"
    module_structure: true
    import_organization: true
    license_compliance: true

# Reporting templates
report_templates:
  # HTML report template
  html:
    template: "templates/conformity-report.html"
    css: "templates/conformity-styles.css"
    javascript: "templates/conformity-scripts.js"
    
  # Markdown report template  
  markdown:
    template: "templates/conformity-report.md"
    
  # JSON schema
  json:
    schema: "schemas/conformity-report-schema.json"
    
  # PDF settings
  pdf:
    template: "templates/conformity-report-pdf.html"
    paper_size: "A4"
    margins: "1cm"

# Dashboard configuration
dashboard:
  enabled: true
  refresh_interval: "5m"
  metrics_retention: "30d"
  real_time_updates: true
  
  # Widgets configuration
  widgets:
    - type: "ecosystem_health"
      position: [0, 0]
      size: [4, 2]
      
    - type: "manager_scores"
      position: [4, 0] 
      size: [4, 2]
      
    - type: "trend_chart"
      position: [0, 2]
      size: [8, 3]
      
    - type: "issue_tracker"
      position: [0, 5]
      size: [4, 3]
      
    - type: "compliance_badges"
      position: [4, 5]
      size: [4, 3]

# Advanced features
advanced:
  # AI-powered suggestions
  ai_suggestions:
    enabled: false  # Future feature
    model: "gpt-4"
    confidence_threshold: 0.8
    
  # Predictive analytics
  predictive:
    enabled: true
    trend_analysis: true
    regression_detection: true
    improvement_recommendations: true
    
  # Integration with external tools
  integrations:
    sonarqube:
      enabled: false
      url: ""
      token: ""
      
    github_actions:
      enabled: true
      workflow_trigger: true
      
    slack:
      enabled: false
      webhook_url: ""
      channel: "#conformity"
