version: '3'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - N8N_AUTH_EXCLUDE_ENDPOINTS=*
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_HIRING_BANNER_ENABLED=false
      - N8N_TEMPLATES_ENABLED=false
      - N8N_TEMPLATES_HOST=https://api.n8n.io/
      - N8N_PUBLIC_API_DISABLED=true
      - NODE_ENV=development
      - N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN=true
      - N8N_SECURE_COOKIE=false
      - N8N_ENCRYPTION_KEY=12345678901234567890123456789012
    volumes:
      - ./n8n-data:/home/node/.n8n
