#
# Module manifest for module 'RoadmapParser'
#
# Generated by: RoadmapParser Team
#
# Generated on: 2023-07-15
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule           = 'RoadmapParser.psm1'

    # Version number of this module.
    ModuleVersion        = '0.1.0'

    # Supported PSEditions
    CompatiblePSEditions = @('Desktop', 'Core')

    # ID used to uniquely identify this module
    GUID                 = '8f7c5f5e-9b5a-4c1a-8f5e-9b5a4c1a8f5e'

    # Author of this module
    Author               = 'RoadmapParser Team'

    # Company or vendor of this module
    CompanyName          = 'Unknown'

    # Copyright statement for this module
    Copyright            = '(c) 2023 RoadmapParser Team. All rights reserved.'

    # Description of the functionality provided by this module
    Description          = 'A PowerShell module for parsing and manipulating roadmap files in Markdown format.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion    = '5.1'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport    = @(
        'ConvertFrom-MarkdownToRoadmap',
        'ConvertFrom-MarkdownToRoadmapExtended',
        'ConvertFrom-MarkdownToRoadmapOptimized',
        'ConvertFrom-MarkdownToRoadmapWithDependencies',
        'Test-MarkdownFormat',
        'Edit-RoadmapTask',
        'Find-DependencyCycle',
        'Get-TaskDependencies',
        'Export-RoadmapToJson',
        'Import-RoadmapFromJson',
        'Select-RoadmapTask',
        'Test-RoadmapParameter',
        'Get-RoadmapParameterDefault',
        'Initialize-RoadmapParameters',
        'Test-RoadmapReturnType',
        'Write-RoadmapLog',
        'Invoke-RoadmapErrorHandler',
        'Test-RoadmapInput',
        'ConvertTo-RoadmapFormat',
        'ConvertFrom-RoadmapFormat',
        'Format-RoadmapString',
        'Search-RoadmapString',
        'Measure-RoadmapString',
        'ConvertTo-NormalizedPath',
        'Test-PathValidity',
        'Resolve-PathToAbsolute',
        'Join-PathSegments',
        'Set-RoadmapLogLevel',
        'Get-RoadmapLogConfiguration',
        'Set-RoadmapLogDestination',
        'Set-RoadmapLogFormat',
        'Write-RoadmapDebug',
        'Write-RoadmapVerbose',
        'Write-RoadmapInformation',
        'Write-RoadmapWarning',
        'Write-RoadmapError',
        'Write-RoadmapCritical',
        'Inspect-Variable',
        # Points d'arrÃªt conditionnels
        'Set-RoadmapBreakpoint',
        'Test-RoadmapBreakpointCondition',
        'Invoke-RoadmapBreakpointAction',
        'Write-RoadmapBreakpointLog',
        'Set-RoadmapTimedBreakpoint',
        # Fonctions de gestion d'erreurs
        'Handle-Error',
        'Invoke-WithRetry',
        'Get-ExceptionInfo',
        'Get-ExceptionCategory',
        'Get-ExceptionSeverity',
        # Fonctions de journalisation
        'Set-LoggingConfiguration',
        'Write-LogDebug',
        'Write-LogInfo',
        'Write-LogWarning',
        'Write-LogError',
        'Get-LoggingConfiguration',
        'New-LogFile',
        # Fonctions de rotation des logs
        'Invoke-LogRotation',
        'Clear-OldLogFiles',
        'Compress-LogFile',
        # Fonctions d'analyse SQL Server
        'Analyze-SqlServerPermission',
        'Get-SqlPermissionRules'
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport      = @()

    # Variables to export from this module
    VariablesToExport    = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport      = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData          = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags         = @('Roadmap', 'Markdown', 'Parser', 'Project-Management')

            # A URL to the license for this module.
            # LicenseUri = ''

            # A URL to the main website for this project.
            # ProjectUri = ''

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            ReleaseNotes = 'Initial release of the RoadmapParser module.'

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfoURI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}
