#
# Module manifest for module 'RoadmapParserCore'
#
# Generated by: RoadmapParser Team
#
# Generated on: 2023-08-15
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule           = 'RoadmapParserCore.psm1'

    # Version number of this module.
    ModuleVersion        = '0.2.0'

    # Supported PSEditions
    CompatiblePSEditions = @('Desktop', 'Core')

    # ID used to uniquely identify this module
    GUID                 = '9c7f8e5d-6a5b-4e7c-9a3a-f8d2e9b7c5d5'

    # Author of this module
    Author               = 'RoadmapParser Team'

    # Company or vendor of this module
    CompanyName          = 'EMAIL_SENDER_1'

    # Copyright statement for this module
    Copyright            = '(c) 2023 RoadmapParser Team. All rights reserved.'

    # Description of the functionality provided by this module
    Description          = 'Module central pour l''analyse, la manipulation et la gestion des roadmaps en format markdown'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion    = '5.1'

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport    = '*'

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport      = @()

    # Variables to export from this module
    VariablesToExport    = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport      = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData          = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags         = @('Roadmap', 'Markdown', 'Parser', 'Project-Management', 'Task-Management')

            # ReleaseNotes of this module
            ReleaseNotes = 'Version unifiÃ©e du module RoadmapParser avec chargement dynamique des fonctions et support des modes opÃ©rationnels.'

        } # End of PSData hashtable
    } # End of PrivateData hashtable
}
