# PowerShell script for SOTA+++ structure creation (Windows compatible)
$PROJECT_ROOT = "2025-0807-visu-interactiv-orch-mode2"

$folders = @(
   "$PROJECT_ROOT/",
   "$PROJECT_ROOT/0-ARCHITECTURE-DECISION-RECORDS/",
   "$PROJECT_ROOT/0-GOVERNANCE/",
   "$PROJECT_ROOT/ideation/design-research/user-interviews/",
   "$PROJECT_ROOT/ideation/design-research/competitive-analysis/",
   "$PROJECT_ROOT/ideation/design-research/market-research/",
   "$PROJECT_ROOT/ideation/explorations/",
   "$PROJECT_ROOT/ideation/syntheses/",
   "$PROJECT_ROOT/ideation/precedents/",
   "$PROJECT_ROOT/ideation/innovation-lab/",
   "$PROJECT_ROOT/projet/business-model/",
   "$PROJECT_ROOT/projet/stakeholder-management/",
   "$PROJECT_ROOT/projet/roadmap/quarterly-okrs/",
   "$PROJECT_ROOT/projet/roadmap/release-planning/",
   "$PROJECT_ROOT/projet/documentation/api-specifications/",
   "$PROJECT_ROOT/projet/documentation/architecture-docs/",
   "$PROJECT_ROOT/projet/documentation/user-guides/",
   "$PROJECT_ROOT/projet/feedback/user-feedback/",
   "$PROJECT_ROOT/projet/feedback/stakeholder-feedback/",
   "$PROJECT_ROOT/projet/feedback/team-retrospectives/",
   "$PROJECT_ROOT/projet/validation/business-validation/",
   "$PROJECT_ROOT/projet/validation/technical-validation/",
   "$PROJECT_ROOT/projet/validation/user-validation/",
   "$PROJECT_ROOT/projet/metrics-analytics/performance-reports/",
   "$PROJECT_ROOT/dev/architecture/system-design/",
   "$PROJECT_ROOT/dev/architecture/microservices/",
   "$PROJECT_ROOT/dev/architecture/data-architecture/",
   "$PROJECT_ROOT/dev/architecture/infrastructure/",
   "$PROJECT_ROOT/dev/implementation/backend/",
   "$PROJECT_ROOT/dev/implementation/frontend/",
   "$PROJECT_ROOT/dev/implementation/shared/",
   "$PROJECT_ROOT/dev/implementation/integrations/",
   "$PROJECT_ROOT/dev/infrastructure-as-code/terraform/",
   "$PROJECT_ROOT/dev/infrastructure-as-code/kubernetes/",
   "$PROJECT_ROOT/dev/infrastructure-as-code/helm-charts/",
   "$PROJECT_ROOT/dev/infrastructure-as-code/ansible/",
   "$PROJECT_ROOT/dev/ui-ux-design-system/design-tokens/",
   "$PROJECT_ROOT/dev/ui-ux-design-system/component-library/",
   "$PROJECT_ROOT/dev/ui-ux-design-system/prototypes/",
   "$PROJECT_ROOT/dev/ui-ux-design-system/accessibility/",
   "$PROJECT_ROOT/dev/interactivite/",
   "$PROJECT_ROOT/dev/observability/logging/",
   "$PROJECT_ROOT/dev/observability/metrics/",
   "$PROJECT_ROOT/dev/observability/tracing/",
   "$PROJECT_ROOT/dev/observability/alerting/",
   "$PROJECT_ROOT/dev/security/threat-modeling/",
   "$PROJECT_ROOT/dev/security/penetration-testing/",
   "$PROJECT_ROOT/dev/security/secrets-management/",
   "$PROJECT_ROOT/dev/security/compliance/",
   "$PROJECT_ROOT/dev/data-engineering/etl-pipelines/",
   "$PROJECT_ROOT/dev/data-engineering/data-quality/",
   "$PROJECT_ROOT/dev/data-engineering/analytics/",
   "$PROJECT_ROOT/dev/data-engineering/governance/",
   "$PROJECT_ROOT/dev/audit/",
   "$PROJECT_ROOT/dev/benchmarks/",
   "$PROJECT_ROOT/dev/matrices/",
   "$PROJECT_ROOT/dev/reporting/",
   "$PROJECT_ROOT/dev/disaster-recovery/backup-procedures/",
   "$PROJECT_ROOT/dev/disaster-recovery/failover-testing/",
   "$PROJECT_ROOT/dev/disaster-recovery/incident-response/",
   "$PROJECT_ROOT/dev/rollback/",
   "$PROJECT_ROOT/dev/scripts/",
   "$PROJECT_ROOT/dev/testing/unit-testing/",
   "$PROJECT_ROOT/dev/testing/integration-testing/",
   "$PROJECT_ROOT/dev/testing/e2e-testing/",
   "$PROJECT_ROOT/dev/testing/performance-testing/",
   "$PROJECT_ROOT/dev/testing/security-testing/",
   "$PROJECT_ROOT/dev/testing/accessibility-testing/",
   "$PROJECT_ROOT/dev/api-gateway/rate-limiting/",
   "$PROJECT_ROOT/dev/api-gateway/authentication/",
   "$PROJECT_ROOT/dev/api-gateway/documentation/",
   "$PROJECT_ROOT/dev/api-gateway/versioning/",
   "$PROJECT_ROOT/dev/exceptions/",
   "$PROJECT_ROOT/dev/guides-llm-robustesse/prompt-engineering/",
   "$PROJECT_ROOT/dev/guides-llm-robustesse/model-evaluation/",
   "$PROJECT_ROOT/dev/guides-llm-robustesse/ai-safety/",
   "$PROJECT_ROOT/dev/versionning/",
   "$PROJECT_ROOT/environments/development/",
   "$PROJECT_ROOT/environments/staging/",
   "$PROJECT_ROOT/environments/production/",
   "$PROJECT_ROOT/environments/sandbox/",
   "$PROJECT_ROOT/cmd/",
   "$PROJECT_ROOT/assets/images/",
   "$PROJECT_ROOT/assets/icons/",
   "$PROJECT_ROOT/assets/fonts/",
   "$PROJECT_ROOT/assets/media/",
   "$PROJECT_ROOT/.github/workflows/",
   "$PROJECT_ROOT/.github/ISSUE_TEMPLATE/",
   "$PROJECT_ROOT/.github/PULL_REQUEST_TEMPLATE/",
   "$PROJECT_ROOT/docs-as-code/confluence-sync/",
   "$PROJECT_ROOT/docs-as-code/api-docs-generation/",
   "$PROJECT_ROOT/docs-as-code/changelog-automation/",
   "$PROJECT_ROOT/.vscode/"
)

$files = @(
   "$PROJECT_ROOT/0-README.md",
   "$PROJECT_ROOT/0-ARCHITECTURE-DECISION-RECORDS/README.md",
   "$PROJECT_ROOT/0-GOVERNANCE/data-governance.md",
   "$PROJECT_ROOT/0-GOVERNANCE/security-policies.md",
   "$PROJECT_ROOT/0-GOVERNANCE/compliance-matrix.csv",
   "$PROJECT_ROOT/0-GOVERNANCE/risk-assessment.md",
   "$PROJECT_ROOT/ideation/0-ideation-process.md",
   "$PROJECT_ROOT/projet/vision.md",
   "$PROJECT_ROOT/projet/roadmap/strategic-roadmap.md",
   "$PROJECT_ROOT/projet/metrics-analytics/kpi-dashboard.md",
   "$PROJECT_ROOT/projet/metrics-analytics/analytics-setup.md",
   "$PROJECT_ROOT/dev/ui-ux-design-system/design-tokens/README.md",
   "$PROJECT_ROOT/dev/ui-ux-design-system/component-library/README.md",
   "$PROJECT_ROOT/dev/ui-ux-design-system/prototypes/README.md",
   "$PROJECT_ROOT/dev/ui-ux-design-system/accessibility/README.md",
   "$PROJECT_ROOT/dev/audit/audit-procedure.md",
   "$PROJECT_ROOT/dev/benchmarks/bench_targets.md",
   "$PROJECT_ROOT/dev/matrices/compat_matrix.md",
   "$PROJECT_ROOT/dev/testing/README.md",
   "$PROJECT_ROOT/dev/guides-llm-robustesse/guide_llm.md",
   "$PROJECT_ROOT/environments/development/README.md",
   "$PROJECT_ROOT/environments/staging/README.md",
   "$PROJECT_ROOT/environments/production/README.md",
   "$PROJECT_ROOT/environments/sandbox/README.md",
   "$PROJECT_ROOT/cmd/README.md",
   "$PROJECT_ROOT/.github/workflows/ci.yml",
   "$PROJECT_ROOT/.github/workflows/cd-staging.yml",
   "$PROJECT_ROOT/.github/workflows/cd-production.yml",
   "$PROJECT_ROOT/.github/workflows/security-scan.yml",
   "$PROJECT_ROOT/.github/workflows/dependency-update.yml",
   "$PROJECT_ROOT/.github/ISSUE_TEMPLATE/bug_report.yml",
   "$PROJECT_ROOT/.github/ISSUE_TEMPLATE/feature_request.yml",
   "$PROJECT_ROOT/.github/ISSUE_TEMPLATE/security_vulnerability.yml",
   "$PROJECT_ROOT/.github/PULL_REQUEST_TEMPLATE/pull_request_template.md",
   "$PROJECT_ROOT/.github/CODEOWNERS",
   "$PROJECT_ROOT/.github/dependabot.yml",
   "$PROJECT_ROOT/docs-as-code/README.md",
   "$PROJECT_ROOT/docs-as-code/confluence-sync/README.md",
   "$PROJECT_ROOT/docs-as-code/api-docs-generation/README.md",
   "$PROJECT_ROOT/docs-as-code/changelog-automation/README.md",
   "$PROJECT_ROOT/.vscode/settings.json",
   "$PROJECT_ROOT/.vscode/extensions.json",
   "$PROJECT_ROOT/.vscode/launch.json",
   "$PROJECT_ROOT/.vscode/tasks.json"
)

foreach ($folder in $folders) {
   if (!(Test-Path $folder)) {
      New-Item -ItemType Directory -Path $folder | Out-Null
   }
}

foreach ($file in $files) {
   if (!(Test-Path $file)) {
      New-Item -ItemType File -Path $file | Out-Null
   }
}

Write-Host "Structure complète pour $PROJECT_ROOT créée avec succès (compatible Windows/PowerShell)."
