---
to: commands/<%= name %>.ps1
---
<%
const { createLogger } = require('../../helpers/logger-helper.js');
const logger = createLogger({ verbosity: 'info', useEmoji: true });
logger.info(`Generating command file: ${name}.ps1`);
%>
<#
.SYNOPSIS
    <%= description %>

.DESCRIPTION
    <%= description %>
    Generated on <%= new Date().toISOString().split('T')[0] %>

.PARAMETER <%= parameters[0] %>
    First parameter of the command

<% parameters.slice(1).forEach(param => { -%>
.PARAMETER <%= param %>
    Additional parameter for the command
<% }) -%>

.EXAMPLE
    <%= name %> -<%= parameters[0] %> value

.NOTES
    Generated by Mode Command Template
#>
function <%= name %> {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$<%= parameters[0] %><% parameters.slice(1).forEach(param => { %>,

        [Parameter(Mandatory = $false)]
        [string]$<%= param %><% }) %>
    )

    # Initialize logging
    $logger = Get-Logger
    $logger.info("Starting <%= name %> command execution")
    
    try {
        # Command implementation here
        $logger.debug("Processing command parameters")
        
        # Main logic
        $logger.info("Executing main command logic")
        
        # Success
        $logger.success("Command executed successfully")
    }
    catch {
        $logger.error("Error executing command: $($_.Exception.Message)")
        throw
    }
}
