name: Full CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Run unit tests
        run: go test ./...
      - name: Run benchmarks
        run: go test -bench=. ./...
      - name: Run coverage
        run: go test -coverprofile=coverage.out ./...
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.out
      - name: Lint
        run: golint ./...
      - name: Security scan
        run: gosec ./...
      - name: Notify on failure
        if: failure()
        run: echo "Notification: CI/CD pipeline failed!" # À remplacer par une vraie notification (Slack, mail...)

badges:
  - name: CI
    image: https://github.com/OWNER/REPO/actions/workflows/full-ci.yml/badge.svg
    alt: "CI Status"