jobs:
  detect-and-redirect:
    if: github.actor == 'google-labs-jules[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure Git
        run: |
          git config --global user.name "Jules Bot Redirect Manager"
          git config --global user.email "actions@github.com"
      - id: branch-check
        name: Check Current Branch
        run: |
          CURRENT_BRANCH="${{ github.ref_name }}"
          echo "current_branch=$CURRENT_BRANCH" >> $GITHUB_OUTPUT
          echo "Current branch: $CURRENT_BRANCH"

          # Check if already in jules-google namespace
          if [[ "$CURRENT_BRANCH" == jules-google/* ]]; then
            echo "already_redirected=true" >> $GITHUB_OUTPUT
            echo "Branch already in jules-google namespace"
          else
            echo "already_redirected=false" >> $GITHUB_OUTPUT
            echo "Branch needs redirection"
          fi
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.branch-check.outputs.already_redirected == 'false'
        name: Create Redirect Branch
        run: |
          CURRENT_BRANCH="${{ steps.branch-check.outputs.current_branch }}"
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          NEW_BRANCH="jules-google/auto-redirect-$TIMESTAMP-$CURRENT_BRANCH"

          echo "Creating redirect branch: $NEW_BRANCH"

          # Create and push the redirect branch
          git checkout -b "$NEW_BRANCH"
          git push origin "$NEW_BRANCH"

          echo "✅ Redirect branch created: $NEW_BRANCH"
          echo "✅ Original content preserved and redirected"
      - if: steps.branch-check.outputs.already_redirected == 'false'
        name: Log Redirect Activity
        run: "echo \"\U0001F916 Jules Bot Redirect Activity Log\"\necho \"=================================\"\necho \"Timestamp: $(date -u +\"%Y-%m-%d %H:%M:%S UTC\")\"\necho \"Repository: ${{ github.repository }}\"\necho \"Original Branch: ${{ steps.branch-check.outputs.current_branch }}\"\necho \"Event Type: ${{ github.event_name }}\"\necho \"Commit SHA: ${{ github.sha }}\"\necho \"Redirect Status: SUCCESS\"\necho \"Protection Level: ACTIVE\"\n"
name: Jules Bot Redirect Handler
"on":
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
