name: Load Tests

on:
  push:
    branches: [ main ]

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Run load tests
        run: go run load_test.go
      - name: Archive load logs
        uses: actions/upload-artifact@v3
        with:
          name: load-logs
          path: load_report.md